### ISSUE TITLE
ERROR [2/2] COPY target/*.jar app  0.4s

### ISSUE THREAD

**Issue by sherry122232** [purshink/ReactJS-Spring-Boot-Full-Stack-App#19]
When I built this: docker-compose up --build, it gives me an issue that :
<img width="504" alt="image" src="https://user-images.githubusercontent.com/45084681/209275813-c1bc3012-0951-45d3-841f-ffb35433a121.png">
Can you help me with that? I don't know what caused this problem. Thanks a lot.

**Comment by prathiksha1909** [comment]
The same issue I'm facing. How do I solve it?

**Comment by fron02315** [comment]
It is solved after running main function in intelliJ
